### PR TITLE
Update Nairobi LUG website

### PR DESCRIPTION
**Pull request by bkmgit**

### CODE REVIEW

**Review by linkeefe — COMMENTED** [review]
Thanks Ben, let me change the title from 'link' to 'github' before merging.

**Comment by bkmgit** [comment]
Thanks for the review. Can do this.

**Comment by bkmgit** [comment]
Updated sponsor information as well. Not sure what else is needed to change the title from `link` to `github`

**Comment by linkeefe** [comment]
No worries, I'll update in my end by EOD today.

**Pull request merged**
